#!/bin/bash

echo "=================================================="
echo "  Push AI Voice Receptionist to Your GitHub"
echo "=================================================="
echo ""
echo "✅ Git repository initialized"
echo "✅ All files committed (30 files, 10,320+ lines)"
echo "✅ .env files safely ignored"
echo ""
echo "=================================================="
echo "  Next Steps:"
echo "=================================================="
echo ""
echo "1️⃣  CREATE GITHUB REPOSITORY"
echo "   Go to: https://github.com/new"
echo "   Repository name: ai-voice-receptionist"
echo "   Description: AI Voice Receptionist SaaS for Karnataka"
echo "   Visibility: Private (recommended)"
echo "   ⚠️  DO NOT initialize with README"
echo ""
echo "2️⃣  COPY YOUR GITHUB USERNAME"
echo "   Example: YOUR_GITHUB_USERNAME"
echo ""
echo "3️⃣  RUN THESE COMMANDS:"
echo ""
echo "   cd /app/voice-receptionist"
echo ""
echo "   # Replace YOUR_GITHUB_USERNAME with your actual username"
echo "   git remote add origin https://github.com/YOUR_GITHUB_USERNAME/ai-voice-receptionist.git"
echo ""
echo "   # Rename branch to main"
echo "   git branch -M main"
echo ""
echo "   # Push to GitHub"
echo "   git push -u origin main"
echo ""
echo "=================================================="
echo "  Alternative: Use GitHub CLI"
echo "=================================================="
echo ""
echo "   # If you have GitHub CLI installed"
echo "   gh auth login"
echo "   gh repo create ai-voice-receptionist --private --source=. --push"
echo ""
echo "=================================================="
echo "  What Gets Pushed:"
echo "=================================================="
echo ""
echo "✅ Complete backend (Node.js + Express + Exotel)"
echo "✅ Frontend setup (Next.js 14)"
echo "✅ Database schema (Supabase PostgreSQL)"
echo "✅ All documentation (5 comprehensive guides)"
echo "✅ Configuration examples (.env.example)"
echo ""
echo "⛔ NOT Pushed (Protected):"
echo ""
echo "❌ .env files (with your API keys)"
echo "❌ node_modules"
echo "❌ Build artifacts"
echo ""
echo "=================================================="
echo "  After Pushing:"
echo "=================================================="
echo ""
echo "Your repository will be at:"
echo "https://github.com/YOUR_GITHUB_USERNAME/ai-voice-receptionist"
echo ""
echo "Ready to deploy to:"
echo "• Railway.app (backend)"
echo "• Vercel (frontend)"
echo "• Already using Supabase (database)"
echo ""
echo "=================================================="
